### ISSUE TITLE
Use custom gRPC implementation with Helidon

### ISSUE THREAD

**Issue by a-saksena** [hashgraph/hedera-block-node#180]
As a Block Node developer
I want to replace Helidon's OOTB gRPC layer with our custom PBJ implementation
So that, I have greater control of the gRPC layer
```[tasklist]
### Tasks
- [x] Replace `server` subproject `grpc.io` gradle dependencies with PBJ's Helidon plugin
- [x] Remove protoc/PBJ Translator code
- [x] Re-implement `grpc.io` integration to align with the Helidon plugin types, etc
- [x] Test our 3 gRPC method types: Unary, Server Streaming, Bidirectional
- [x] Repair Block Node unit tests
- [x] Fix simulator to work with protoc types and remove PBJ types
```

**Comment by mattp-swirldslabs** [comment]
Created PBJ [bug ticket](https://github.com/hashgraph/pbj/issues/300) to document issues with Server Streaming integration.

**Comment by mattp-swirldslabs** [comment]
Created PBJ [feature ticket](https://github.com/hashgraph/pbj/issues/303) to document framework gaps when clients cancel or close connections to the Block Node.
