### ISSUE TITLE
EPIC: E2E Test Plan

### ISSUE THREAD

**Issue by georgi-l95** [hashgraph/hedera-block-node#183]
This issue aims to describe the e2e test plan for the Block Node, each sub-plan divided by service (eg. Storage, State)

```[tasklist]
### gRPC
- [ ] https://github.com/hashgraph/hedera-block-node/issues/184
- [ ] https://github.com/hashgraph/hedera-block-node/issues/186
```

```[tasklist]
### Storage
- [ ] https://github.com/hashgraph/hedera-block-node/issues/187
```

**Disclaimer:** Test Plan is incomplete and subject to changes and extentions.

**Comment by a-saksena** [comment]
Carve out a separate Epic for Ph-2 for the remaining work. @georgi-l95
