### ISSUE TITLE
EPIC: Estimate Infrastructure requirements

### ISSUE THREAD

**Issue by a-saksena** [hashgraph/hedera-block-node#221]
```[tasklist]
### Estimates
- [ ] https://github.com/hashgraph/hedera-block-node/issues/222
- [ ] https://github.com/hashgraph/hedera-block-node/issues/219
- [ ] https://github.com/hashgraph/hedera-block-node/issues/223
- [ ] https://github.com/hashgraph/hedera-block-node/issues/220
```
