### ISSUE TITLE
EPIC: Change Block Node to process repeated block items

### ISSUE THREAD

**Issue by jsync-swirlds** [hashgraph/hedera-block-node#247]
```[tasklist]
### Modifications to BlockStream and API definitions
- [ ] https://github.com/hashgraph/hedera-block-node/issues/259
```
```[tasklist]
### Modifications to the BlockNode codebase
- [ ] https://github.com/hashgraph/hedera-block-node/issues/261
- [ ] https://github.com/hashgraph/hedera-block-node/issues/262
- [ ] https://github.com/hashgraph/hedera-block-node/issues/268
- [ ] https://github.com/hashgraph/hedera-block-node/issues/270
- [ ] https://github.com/hashgraph/hedera-block-node/issues/276
- [ ] https://github.com/hashgraph/hedera-block-node/issues/277
- [x] Update bash tools to support repeated BlockItem(s).
- [x] Modify / Update the documentation to reflect the changes to the server
```
```[tasklist]
### Modifications to the Simulator
- [ ] https://github.com/hashgraph/hedera-block-node/issues/278
- [ ] https://github.com/hashgraph/hedera-block-node/issues/279
- [x] Modify Documentation to reflect the changes to the simulator
- [ ] https://github.com/hashgraph/hedera-block-node/issues/288
```
