### ISSUE TITLE
EPIC: Introduce Common module

### ISSUE THREAD

**Issue by georgi-l95** [hashgraph/hedera-block-node#254]
## Story
**AS A** Block Node Developer
**I WANT** to have an easily accessible module that could be used by any project and holds common, generic, reusable logic.
**SO THAT** we have good architecture and easily available place to abstract generic logic

## Tech Notes
- this improvement requires that we introduce a new module, call it `common`, and abstract already existing logic that fits the module there.
- the general philosophy for the module is:
    - must be looked at as an `external dependency` in the sense that it must not have any logic that is coupled or related to any specific project
    - to support the previous point, the module must be `readily exportable` and `reusable` by anyone anywhere anytime
    - simply, all components of the module must be reusable anywhere, regardless of the nature of the project that uses it
    - any changes to the module should be very thoroughly discussed and thought through

## Tasklist
```[tasklist]
### Common Module Task List
- [ ] https://github.com/hashgraph/hedera-block-node/issues/233
- [ ] https://github.com/hashgraph/hedera-block-node/issues/252
- [ ] https://github.com/hashgraph/hedera-block-node/issues/253
- [ ] https://github.com/hashgraph/hedera-block-node/issues/273
```
