### ISSUE TITLE
Clean-up Release 99.99.99-draft

### ISSUE THREAD

**Issue by AlfredoG87** [hashgraph/hedera-block-node#255]
### Tasks
- [x] Delete Helm artifact `hedera-block-node-99.99.99-draft.tgz` from `gh-page` branch https://github.com/hashgraph/hedera-block-node/tree/gh-pages/charts.
- [x] Delete Draft Release for `99.99.99-draft` from `Releases` Section of the Repo.

**The next 2 tasks required Admin Access Role to the Block-Node Repo**

- [x] Deleted Release branch `release/99.99` https://github.com/hashgraph/hedera-block-node/branches/all?query=release/99.99
- [x] Delete Container image `99.99.99-draft` from repo https://github.com/hashgraph/hedera-block-node/pkgs/container/hedera-block-node
- [x] remove Tag from here: https://github.com/hashgraph/hedera-block-node/tags

**Comment by AlfredoG87** [comment]
Everything is clean now. Thanks @Nana-EC for your help too!!

**Comment by AlfredoG87** [comment]
Tag has been removed!
