### ISSUE TITLE
EPIC: Improve documentation

### ISSUE THREAD

**Issue by georgi-l95** [hashgraph/hedera-block-node#265]
This EPIC aims to improve the current documentation and introduce a process and structure for adding design documents.
```[tasklist]
### Documentation Tasks
- [ ] https://github.com/hashgraph/hedera-block-node/issues/263
- [ ] https://github.com/hashgraph/hedera-block-node/issues/320
- [ ] https://github.com/hashgraph/hedera-block-node/issues/325
```
