### ISSUE TITLE
EPIC: Essential Local Block Storage & Retrieval Support

### ISSUE THREAD

**Issue by jsync-swirlds** [hashgraph/hedera-block-node#309]
## Epic Goal
Design/implementation for essential block storage and retrieval support to enable the Phase 2 block node features (pre-release).

In this first iteration of the persistence layer, it is important to lay the ground work, to streamline the process and to see it work. Once everything is wired up and running, we will be able to iterate over this base in later iterations to introduce improvements to the persistence layer and clear out any uncertainties.

See #125 where we have defined the design of the functionality that now we need to implement

```[tasklist]
### Tasks (in recommended order of implementation)
- [ ] https://github.com/hashgraph/hedera-block-node/issues/281
- [ ] https://github.com/hashgraph/hedera-block-node/issues/319
- [ ] https://github.com/hashgraph/hedera-block-node/issues/348
- [ ] https://github.com/hashgraph/hedera-block-node/issues/349
- [ ] https://github.com/hashgraph/hedera-block-node/issues/282
- [ ] https://github.com/hashgraph/hedera-block-node/issues/350
- [ ] https://github.com/hashgraph/hedera-block-node/issues/339
- [ ] https://github.com/hashgraph/hedera-block-node/issues/351
- [ ] https://github.com/hashgraph/hedera-block-node/issues/370
- [ ] https://github.com/hashgraph/hedera-block-node/issues/381
```
