### ISSUE TITLE
EPIC: Repackage existing record files in the Block Stream.

### ISSUE THREAD

**Issue by jsync-swirlds** [hashgraph/hedera-block-node#328]
As Hedera
We Want to repackage the record files in the Block Stream
So That We can reduce the total storage needed, improve financial efficiency, and unify access to block chain data via block nodes only.

```tasklist
# Required Actions
- [ ] Create a tool to convert existing record files to block files
   - [ ] Read a record file
   - [ ] (Optional) Split the record file into one entry per round
         (may not be technically possible).
   - [ ] Read and verify all available signature files
   - [ ] wrap the record file data and all signatures in a `RecordFile` `BlockItem`
   - [ ] Wrap the `BlockItem` in a `Block`.
   - [ ] Write the `Block` to disk, using zstd compression
   - [ ] Verify the written block
   - [ ] Repeat for all record files (roughly 160 million)
- [ ] Launch a VM in GCP or AWS _local_ to the record file archive(s).
- [ ] Run the conversion tool on groups of 100,000 record files.
   - [ ] Create an _uncompressed_ ZIP file for each group
   - [ ] Upload the new ZIP file to a new storage bucket
- [ ] Work with Mirror Node team to read the ZIP files, extract blocks, and verify
      that the mirror node import process can still work with the new files.
```

**Comment by Mark-Swirlds** [comment]
Do we need to capture the node account ID info in the path w/ these wrapped records?

**Comment by jsync-swirlds** [comment]
> Do we need to capture the node account ID info in the path w/ these wrapped records?
No.  We only keep 1 copy of the result blocks, and it doesn't matter which node produced each block, as they're all identical.

**Comment by Nana-EC** [comment]
@jasperpotts , @jsync-swirlds and @rockysingh closing this off as all items are covered
