### ISSUE TITLE
EPIC: Modify Docker build to create Deterministic Images

### ISSUE THREAD

**Issue by AlfredoG87** [hashgraph/hedera-block-node#332]
### Problem
As a consumer of block node application docker images
I want the images to be deterministic
So that, I could reproduce the same image to verify its contents

We need the builds from the block-node docker images to be `deterministic`

### Solution

* Integrate the gradle plugin as it is on `hedera-services` so that we get deterministic software builds
* Use the `hedera-services` Dockerfile and support scripts to ensure deterministic images
* Use the CI GHA yamls and scripts to build and verify the required behavior

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-block-node/issues/408
- [ ] https://github.com/hashgraph/hedera-block-node/issues/409
- [ ] https://github.com/hashgraph/hedera-block-node/issues/410
```

**Comment by mattp-swirldslabs** [comment]
![image](https://github.com/user-attachments/assets/92c94b63-269b-4955-8c96-60fd645e1b95)
* Important piece of deterministic build

**Comment by mattp-swirldslabs** [comment]
![image](https://github.com/user-attachments/assets/6c943121-d32d-4a63-891e-086e316571d7)

**Comment by mattp-swirldslabs** [comment]
![image](https://github.com/user-attachments/assets/e43201bb-5609-4084-bf5f-dd24c1d99e3b)
* Steal this from services

**Comment by mattp-swirldslabs** [comment]
![image](https://github.com/user-attachments/assets/0a301935-38a8-4a33-88e4-200f902fd0cd)
* Pipeline file must use UTF-8 as well

**Comment by mattp-swirldslabs** [comment]
* We'll need a service account for the repo

**Comment by mattp-swirldslabs** [comment]
* Might need to comment out the application section if we don't have multiple jar file directories

**Comment by mattp-swirldslabs** [comment]
![image](https://github.com/user-attachments/assets/16e4564a-5598-4469-a950-3615c9e95d7a)
* Standardize git line endings is also important

**Comment by mattp-swirldslabs** [comment]
![image](https://github.com/user-attachments/assets/d7f03250-1d10-4851-a95a-48954fcbdb42)
* Docker determinism pieces

**Comment by mattp-swirldslabs** [comment]
`SOURCE_DATE_EPOCH="0"` is not valid in later versions of docker build kit

**Comment by mattp-swirldslabs** [comment]
![image](https://github.com/user-attachments/assets/81f6246c-6bc3-443f-85fd-d18a212f6927)
* Script used to make `apt-get` deterministic in the docker build

**Comment by mattp-swirldslabs** [comment]
* Might not need the "Deterministic Build Hack" section but that hasn't been verified.

**Comment by mattp-swirldslabs** [comment]
* S6 overlay may not be required.
* End up with 2 layers in the end?

**Comment by mattp-swirldslabs** [comment]
GHA testing:
![image](https://github.com/user-attachments/assets/9fb4c47c-ea61-419c-b5fe-f34c90062210)

**Comment by mattp-swirldslabs** [comment]
Here's the link to the meeting recording:

https://swirldslabs.zoom.us/rec/share/lW1gRZ0VylhF_2oQ3WO5BQ6eXhGZu3F5pFEA4WoRIm33fFk3_KgSzHw-Xe-g7lMQ.Q-PEc4xN1Vdj3r3H 
Passcode: 2WHJRU@K

**Comment by ata-nas** [comment]
@AlfredoG87 @mattp-swirldslabs maybe #343 could be added here?

**Comment by jsync-swirlds** [comment]
Completed 2025-01-22
