### ISSUE TITLE
EPIC: Set-up release and deployment pipeline

### ISSUE THREAD

**Issue by a-saksena** [hashgraph/hedera-block-node#39]
```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-block-node/issues/44
- [ ] https://github.com/hashgraph/hedera-block-node/issues/45
- [ ] https://github.com/hashgraph/hedera-block-node/issues/54
- [ ] https://github.com/hashgraph/hedera-block-node/issues/49
- [ ] https://github.com/hashgraph/hedera-block-node/issues/50
- [ ] https://github.com/hashgraph/hedera-block-node/issues/53
- [ ] https://github.com/hashgraph/hedera-block-node/issues/65
- [ ] https://github.com/hashgraph/hedera-block-node/issues/80
- [ ] https://github.com/hashgraph/hedera-block-node/issues/79
- [ ] https://github.com/hashgraph/hedera-block-node/issues/109
- [ ] https://github.com/hashgraph/hedera-block-node/issues/229
- [ ] https://github.com/hashgraph/hedera-block-node/issues/257
- [ ] https://github.com/hashgraph/hedera-block-node/issues/255
```

**Comment by a-saksena** [comment]
@jasperpotts 's feedback -- can we Replace the ssh script for launching docker with a Gradle task.

**Comment by AlfredoG87** [comment]
Complete :)
