### ISSUE TITLE
EPIC: Observability (Monitoring, Alerting, Operations) Phase 1

### ISSUE THREAD

**Issue by AlfredoG87** [hashgraph/hedera-block-node#56]
**Sccope:**

1) Use existing Grafana and Prometheus
2) Use Swirlds Base libraries (logging, metrics..)
3) Carefully chose Metrics
4) Use standard tools (to allow usage by others)
5) Dashboard (minimal)
6) Setting up infra as part of the Deployment

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-block-node/issues/66
- [ ] https://github.com/hashgraph/hedera-block-node/issues/69
- [ ] https://github.com/hashgraph/hedera-block-node/issues/68
- [ ] https://github.com/hashgraph/hedera-block-node/issues/96
- [ ] https://github.com/hashgraph/hedera-block-node/issues/94
- [ ] https://github.com/hashgraph/hedera-block-node/issues/85
- [ ] https://github.com/hashgraph/hedera-block-node/issues/67
- [ ] https://github.com/hashgraph/hedera-block-node/issues/149
- [ ] https://github.com/hashgraph/hedera-block-node/issues/150
- [ ] https://github.com/hashgraph/hedera-block-node/issues/151
```
