### ISSUE TITLE
EPIC: Create Block Stream Simulator

### ISSUE THREAD

**Issue by a-saksena** [hashgraph/hedera-block-node#75]
This issue will descibe and capture the work needed to Block Stream Simulator and it's integration with Block Node.

> May have to be created in Services. 

```[tasklist]
### Block Stream Simulator
- [ ] https://github.com/hashgraph/hedera-block-node/issues/76
- [ ] https://github.com/hashgraph/hedera-block-node/issues/106
- [ ] https://github.com/hashgraph/hedera-block-node/issues/108
- [ ] https://github.com/hashgraph/hedera-block-node/issues/158
- [ ] https://github.com/hashgraph/hedera-block-node/issues/159
- [ ] https://github.com/hashgraph/hedera-block-node/issues/107
- [x] Create Test Plan
- [ ] https://github.com/hashgraph/hedera-block-node/issues/190
- [ ] https://github.com/hashgraph/hedera-block-node/issues/191
- [ ] https://github.com/hashgraph/hedera-block-node/issues/239
- [ ] https://github.com/hashgraph/hedera-block-node/issues/120
- [ ] https://github.com/hashgraph/hedera-block-node/issues/224
- [ ] https://github.com/hashgraph/hedera-block-node/issues/314
- [ ] https://github.com/hashgraph/hedera-block-node/issues/315
```

### Requirements
- Should be able to use real data provided from a pre-defined directory.
- Should be able to integrate as a test-client and be used to support E2E Block Node testing.

**Comment by a-saksena** [comment]
Check with Michael Tinker in the Block Node slack channel.

**Comment by georgi-l95** [comment]
EPIC describing the implemented test plan can be found here https://github.com/hashgraph/hedera-block-node/issues/183

**Comment by Nana-EC** [comment]
@AlfredoG87 and @georgi-l95 noted this is complete and phase 2 work has a different EPIC
